//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesTransaction.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_BOTTOM_DAY
    {
        public System.DateTime dateDay { get; set; }
        public int terminalId { get; set; }
        public decimal beginningCash { get; set; }
        public decimal endCash { get; set; }
    
        public virtual TERMINAL TERMINAL { get; set; }
    }
}
