//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesTransaction.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_DETAILS
    {
        public int idTransactionDetails { get; set; }
        public int transactionId { get; set; }
        public int productId { get; set; }
        public string nameItem { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> vatItem { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual TRANSACTIONS TRANSACTIONS { get; set; }
    }
}
