//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesTransaction.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTIONS()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.TRANSACTION_DETAILS = new HashSet<TRANSACTION_DETAILS>();
        }
    
        public int idTransaction { get; set; }
        public System.DateTime transactionDateBegin { get; set; }
        public System.DateTime transactionDateEnd { get; set; }
        public decimal total { get; set; }
        public Nullable<decimal> discountGlobal { get; set; }
        public bool isReturn { get; set; }
        public int vendorId { get; set; }
        public int terminalId { get; set; }
        public int shopId { get; set; }
        public int customerId { get; set; }
        public int statusId { get; set; }
        public int messageId { get; set; }
        public int languageMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual TERMINAL TERMINAL { get; set; }
        public virtual TICKET_MESSAGE TICKET_MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION_DETAILS> TRANSACTION_DETAILS { get; set; }
    }
}
